export const styles = {
  container: {
    padding: "30px",
    backgroundColor: "#1F1F1F",
    boxShadow: "0px 0px 12px rgba(0,0,0,0.1)",
    color: "#E0E0E0",
    minHeight: "100vh",
    fontFamily: "Arial, sans-serif",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  title: {
    fontSize: "28px",
    marginBottom: "30px",
    color: "#4A90E2",
  },
  label: {
    fontSize: "18px",
    marginBottom: "10px",
    alignSelf: "flex-start",
  },
  inputBox: {
    width: "80%",
    fontSize: "16px",
    padding: "12px",
    lineHeight: "24px",
    color: "#E0E0E0",
    backgroundColor: "#282828",
    border: "1px solid #3A3A3A",
    borderRadius: "12px",
    marginBottom: "20px",
    minHeight: "200px",
    outline: "none",
    resize: "vertical",
  },
  button: {
    width: "80%",
    padding: "12px",
    fontSize: "18px",
    color: "#1F1F1F",
    backgroundColor: "#4A90E2",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "background-color 0.3s ease-in-out",
    margin: "10px 0",
  },
  generatedContent: {
    width: "80%",
    padding: "20px",
    backgroundColor: "#282828",
    borderRadius: "12px",
    alignSelf: "flex-start",
  },
  contentTitle: {
    marginBottom: "20px",
    fontSize: "24px",
    color: "#4A90E2",
  },
  searchInput: {
    width: "78%",
    marginRight: "2%",
    padding: "10px",
    fontSize: "16px",
    backgroundColor: "#282828",
    border: "1px solid #3A3A3A",
    borderRadius: "12px",
    color: "#E0E0E0",
  },
  imageList: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "10px",
    marginTop: "20px",
  },
  imageItem: {
    maxWidth: "150px",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "transform 0.3s ease-in-out",
    "&:hover": {
      transform: "scale(1.05)",
    },
  },
};
